"""Validate BRIEF-Acoustics against a Robin-condition sphere solution.

This script is a companion to validation/sphere_scattering/run_validation.py.
It uses the same mesh generator and the same Fortran executable, but asks the
Fortran side to impose a Robin boundary condition:

    robin_a * phi_total + robin_b * d(phi_total)/dn = 0

The Robin case is useful because it checks both sides of the assembled boundary
operator: phi and normal derivative dphi/dn are coupled explicitly.

Set NSBEM_FORMULATION to ``ordinary`` or ``burton-miller`` to run the same
physical case through either final linear system.
"""

from __future__ import annotations

from dataclasses import dataclass
import csv
import importlib.util
import os
from pathlib import Path
import subprocess
import sys

THIS_DIR = Path(__file__).resolve().parent
MODERN_DIR = THIS_DIR.parents[1]
PYTHON_DIR = MODERN_DIR / "python"
ANA_DIR = MODERN_DIR / "ana"
FORTRAN_DIR = MODERN_DIR / "fortran"
SPHERE_VALIDATION_DIR = MODERN_DIR / "validation" / "sphere_scattering"
RESULTS_DIR = THIS_DIR / os.environ.get("NSBEM_RESULTS_NAME", "results")

os.environ.setdefault("MPLCONFIGDIR", str(RESULTS_DIR / ".matplotlib"))
os.environ.setdefault("XDG_CACHE_HOME", str(RESULTS_DIR / ".cache"))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

sys.path.insert(0, str(PYTHON_DIR))
sys.path.insert(0, str(ANA_DIR))

from analytic import estimate_required_terms, robin_sphere_scattered_field, robin_sphere_total_field  # noqa: E402
from brief_acoustics.mesh_io import (  # noqa: E402
    DEFAULT_ELEMENT_TYPE,
    OUTWARD_FROM_SOLID,
    SurfaceMesh,
    exterior_free_term_sign_for,
    write_fortran_mesh,
)

_sphere_spec = importlib.util.spec_from_file_location(
    "sphere_validation_helpers",
    SPHERE_VALIDATION_DIR / "run_validation.py",
)
if _sphere_spec is None or _sphere_spec.loader is None:
    raise ImportError("Unable to load sphere validation helpers")
_sphere_helpers = importlib.util.module_from_spec(_sphere_spec)
sys.modules[_sphere_spec.name] = _sphere_helpers
_sphere_spec.loader.exec_module(_sphere_helpers)

build_sphere_mesh = _sphere_helpers.build_sphere_mesh
plot_component = _sphere_helpers.plot_component
read_nsbem_csv = _sphere_helpers.read_nsbem_csv
relative_l2 = _sphere_helpers.relative_l2
surface_theta = _sphere_helpers.surface_theta
read_element_type_from_environment = _sphere_helpers.read_element_type_from_environment


@dataclass(frozen=True)
class ValidationConfig:
    """Input parameters for the Robin sphere validation case."""

    radius: float = 1.0
    wavenumber: float = 1.0
    subdivisions: int = 2
    element_type: str = DEFAULT_ELEMENT_TYPE
    normal_orientation: str = OUTWARD_FROM_SOLID
    robin_a: float = 1.0
    robin_b: float = 0.5
    formulation: str = "ordinary"


def main() -> int:
    """Run the complete Robin validation workflow."""

    # Quadratic elements are the public default. Environment variables retain
    # an explicit linear path for convergence studies and regression coverage.
    config = ValidationConfig(
        subdivisions=_env_int("NSBEM_SUBDIVISIONS", ValidationConfig.subdivisions),
        element_type=read_element_type_from_environment(),
        formulation=_env_formulation(),
    )
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    mesh = build_sphere_mesh(
        radius=config.radius,
        subdivisions=config.subdivisions,
        element_type=config.element_type,
    )
    mesh_file = RESULTS_DIR / "sphere_mesh.dat"
    nsbem_file = RESULTS_DIR / "nsbem_surface.csv"
    analytic_file = RESULTS_DIR / "analytic_surface.csv"
    comparison_file = RESULTS_DIR / "comparison_surface.csv"
    summary_file = RESULTS_DIR / "summary.txt"

    # The mesh is generated by Python and consumed by Fortran.  The numerical
    # output is then read back into Python for analytical comparison and plots.
    write_fortran_mesh(mesh, mesh_file)
    build_validation_executable()
    run_robin_validation_executable(mesh_file, nsbem_file, config)

    nsbem = read_nsbem_csv(nsbem_file)
    analytic = evaluate_analytical_solution(nsbem, config)
    write_analytic_csv(analytic_file, analytic)
    comparison = write_comparison_csv(comparison_file, nsbem, analytic, config)
    write_plots(comparison)
    write_summary(summary_file, config, mesh, comparison)

    print(f"Wrote Robin validation results to {RESULTS_DIR}")
    print(summary_file.read_text(encoding="utf-8"))
    return 0


def _env_int(name: str, default: int) -> int:
    """Read an optional integer environment variable."""

    value = os.environ.get(name)
    if value is None:
        return default
    return int(value)


def _env_formulation() -> str:
    """Read and validate the requested boundary-integral formulation."""

    value = os.environ.get("NSBEM_FORMULATION", ValidationConfig.formulation).strip().lower()
    if value == "bm":
        value = "burton-miller"
    if value not in {"ordinary", "burton-miller"}:
        raise ValueError("NSBEM_FORMULATION must be 'ordinary' or 'burton-miller'")
    return value


def build_validation_executable() -> None:
    """Compile the Fortran validation executable if needed."""

    subprocess.run(
        ["make", "-C", str(FORTRAN_DIR), "validate-rigid-sphere"],
        check=True,
    )


def run_robin_validation_executable(mesh_file: Path, output_file: Path, config: ValidationConfig) -> None:
    """Run the Fortran solver in Robin-boundary-condition mode."""

    executable = FORTRAN_DIR / "bin" / "validate_rigid_sphere"
    subprocess.run(
        [
            str(executable),
            str(mesh_file),
            str(output_file),
            f"{config.wavenumber:.17g}",
            f"{config.radius:.17g}",
            str(exterior_free_term_sign_for(config.normal_orientation)),
            "robin",
            f"{config.robin_a:.17g}",
            f"{config.robin_b:.17g}",
            config.formulation,
        ],
        check=True,
    )


def evaluate_analytical_solution(nsbem: dict[str, np.ndarray], config: ValidationConfig) -> dict[str, np.ndarray]:
    """Evaluate the analytical Robin solution at the numerical mesh nodes."""

    n_terms = estimate_required_terms(config.wavenumber, config.radius, safety=30)
    phi_sca = robin_sphere_scattered_field(
        nsbem["points"],
        k=config.wavenumber,
        radius=config.radius,
        robin_a=config.robin_a,
        robin_b=config.robin_b,
        n_terms=n_terms,
    )
    phi_total = robin_sphere_total_field(
        nsbem["points"],
        k=config.wavenumber,
        radius=config.radius,
        robin_a=config.robin_a,
        robin_b=config.robin_b,
        n_terms=n_terms,
    )
    return {
        "node_id": nsbem["node_id"],
        "points": nsbem["points"],
        "theta": surface_theta(nsbem["points"]),
        "phi_sca": phi_sca,
        "phi_total": phi_total,
        "n_terms": np.array([n_terms]),
    }


def write_analytic_csv(path: Path, analytic: dict[str, np.ndarray]) -> None:
    """Write analytical nodal values for inspection and plotting."""

    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            [
                "node_id",
                "x",
                "y",
                "z",
                "theta",
                "phi_sca_re",
                "phi_sca_im",
                "phi_total_re",
                "phi_total_im",
            ]
        )
        for node_id, point, theta, phi_sca, phi_total in zip(
            analytic["node_id"],
            analytic["points"],
            analytic["theta"],
            analytic["phi_sca"],
            analytic["phi_total"],
        ):
            writer.writerow(
                [
                    int(node_id),
                    point[0],
                    point[1],
                    point[2],
                    theta,
                    phi_sca.real,
                    phi_sca.imag,
                    phi_total.real,
                    phi_total.imag,
                ]
            )


def write_comparison_csv(
    path: Path,
    nsbem: dict[str, np.ndarray],
    analytic: dict[str, np.ndarray],
    config: ValidationConfig,
) -> dict[str, np.ndarray]:
    """Write node-by-node numerical/analytical differences and Robin residuals."""

    error_sca = nsbem["phi_sca"] - analytic["phi_sca"]
    error_total = nsbem["phi_total"] - analytic["phi_total"]
    # If the boundary condition has been imposed correctly, this residual should
    # be close to zero at every boundary node.
    robin_residual = config.robin_a * nsbem["phi_total"] + config.robin_b * nsbem["dphi_total"]
    result = {
        "node_id": nsbem["node_id"],
        "points": nsbem["points"],
        "theta": analytic["theta"],
        "nsbem_phi_sca": nsbem["phi_sca"],
        "analytic_phi_sca": analytic["phi_sca"],
        "error_sca": error_sca,
        "nsbem_phi_total": nsbem["phi_total"],
        "analytic_phi_total": analytic["phi_total"],
        "error_total": error_total,
        "dphi_total": nsbem["dphi_total"],
        "robin_residual": robin_residual,
        "normal_radial_alignment": nsbem["normal_radial_alignment"],
    }

    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            [
                "node_id",
                "x",
                "y",
                "z",
                "theta",
                "nsbem_phi_sca_re",
                "nsbem_phi_sca_im",
                "analytic_phi_sca_re",
                "analytic_phi_sca_im",
                "error_sca_abs",
                "nsbem_phi_total_re",
                "nsbem_phi_total_im",
                "analytic_phi_total_re",
                "analytic_phi_total_im",
                "error_total_abs",
                "robin_residual_abs",
            ]
        )
        for i, node_id in enumerate(result["node_id"]):
            point = result["points"][i]
            writer.writerow(
                [
                    int(node_id),
                    point[0],
                    point[1],
                    point[2],
                    result["theta"][i],
                    result["nsbem_phi_sca"][i].real,
                    result["nsbem_phi_sca"][i].imag,
                    result["analytic_phi_sca"][i].real,
                    result["analytic_phi_sca"][i].imag,
                    abs(result["error_sca"][i]),
                    result["nsbem_phi_total"][i].real,
                    result["nsbem_phi_total"][i].imag,
                    result["analytic_phi_total"][i].real,
                    result["analytic_phi_total"][i].imag,
                    abs(result["error_total"][i]),
                    abs(result["robin_residual"][i]),
                ]
            )
    return result


def write_plots(comparison: dict[str, np.ndarray]) -> None:
    """Save simple comparison plots for the Robin surface values."""

    order = np.argsort(comparison["theta"])
    theta = comparison["theta"][order]

    plot_component(
        theta,
        comparison["nsbem_phi_sca"][order].real,
        comparison["analytic_phi_sca"][order].real,
        "Robin scattered potential real part",
        "Re(phi_sca)",
        RESULTS_DIR / "surface_scattered_real.png",
    )
    plot_component(
        theta,
        comparison["nsbem_phi_sca"][order].imag,
        comparison["analytic_phi_sca"][order].imag,
        "Robin scattered potential imaginary part",
        "Im(phi_sca)",
        RESULTS_DIR / "surface_scattered_imag.png",
    )
    plt.figure(figsize=(8, 5))
    plt.semilogy(theta, np.abs(comparison["error_sca"][order]), "o", markersize=3)
    plt.xlabel("theta [rad]")
    plt.ylabel("|NSBEM - analytical|")
    plt.title("Robin scattered potential absolute error")
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(RESULTS_DIR / "surface_error_abs.png", dpi=200)
    plt.close()


def write_summary(
    path: Path,
    config: ValidationConfig,
    mesh: SurfaceMesh,
    comparison: dict[str, np.ndarray],
) -> None:
    """Write a compact Robin validation report."""

    err_sca = np.abs(comparison["error_sca"])
    err_total = np.abs(comparison["error_total"])
    ref_sca = np.abs(comparison["analytic_phi_sca"])
    ref_total = np.abs(comparison["analytic_phi_total"])
    robin_residual = np.abs(comparison["robin_residual"])
    normal_alignment = comparison["normal_radial_alignment"]

    rel_l2_sca = relative_l2(comparison["nsbem_phi_sca"], comparison["analytic_phi_sca"])
    rel_l2_total = relative_l2(comparison["nsbem_phi_total"], comparison["analytic_phi_total"])
    validation_tolerance = 5.0e-2
    validation_status = "PASS" if rel_l2_sca <= validation_tolerance else "FAIL"

    text = "\n".join(
        [
            "Robin sphere BRIEF-Acoustics validation",
            "=================================",
            f"validation status = {validation_status}",
            f"validation tolerance, relative L2 phi_sca = {validation_tolerance:.8e}",
            f"radius = {config.radius:.8g}",
            f"wavenumber = {config.wavenumber:.8g}",
            f"formulation = {config.formulation}",
            f"mesh normal orientation = {config.normal_orientation}",
            f"robin_a = {config.robin_a:.8e}",
            f"robin_b = {config.robin_b:.8e}",
            f"mesh element type = {mesh.element_type}",
            f"mesh nodes per element = {mesh.nodes_per_element}",
            f"mesh nodes = {len(mesh.nodes)}",
            f"mesh elements = {len(mesh.elements)}",
            f"normal radial alignment min = {float(np.min(normal_alignment)):.8e}",
            f"normal radial alignment max = {float(np.max(normal_alignment)):.8e}",
            f"max |phi_sca error| = {float(np.max(err_sca)):.8e}",
            f"rms |phi_sca error| = {float(np.sqrt(np.mean(err_sca**2))):.8e}",
            f"relative L2 phi_sca error = {rel_l2_sca:.8e}",
            f"max |phi_total error| = {float(np.max(err_total)):.8e}",
            f"relative L2 phi_total error = {rel_l2_total:.8e}",
            f"max |Robin residual| = {float(np.max(robin_residual)):.8e}",
            f"reference max |phi_sca| = {float(np.max(ref_sca)):.8e}",
            f"reference max |phi_total| = {float(np.max(ref_total)):.8e}",
            "",
        ]
    )
    path.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
